# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'spotifyApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for spotifyApp
  # pod 'RNAudioStreaming', :path => '../node_modules/react-native-audio-streaming'

  target 'spotifyAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'spotifyApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for spotifyApp-tvOS

  target 'spotifyApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
